// This file is auto-generated by VFXPropertyGenerator.cs
// DO NOT EDIT MANUALLY - Changes will be overwritten
// To modify: Edit VFXPropertyGenerator.cs and regenerate

using System;
using UnityEngine;
using UnityEngine.VFX;

[Serializable]
public abstract class VFXProperty
{
    public string Name;
    [NonSerialized] protected int m_nameID;
    [NonSerialized] protected bool m_isInitialized;

    public abstract void ApplyToVFX(VisualEffect vfx);

    protected void Initialize()
    {
        if (string.IsNullOrEmpty(Name)) return;
        m_nameID = Shader.PropertyToID(Name);
        m_isInitialized = true;
    }
}

[Serializable]
public class AnimationCurveVFXProperty : VFXProperty
{
    public AnimationCurve Value;

    public override void ApplyToVFX(VisualEffect vfx)
    {
        if (!m_isInitialized)
        {
            Initialize();
        }

        if (!m_isInitialized) return; // Guard against empty name

        vfx.SetAnimationCurve(m_nameID, Value);
    }
}

[Serializable]
public class BoolVFXProperty : VFXProperty
{
    public bool Value;
    [NonSerialized] bool m_lastValue;

    public override void ApplyToVFX(VisualEffect vfx)
    {
        if (!m_isInitialized)
        {
            Initialize();
            m_lastValue = Value;
        }

        if (!m_isInitialized) return; // Guard against empty name

        if (Value.Equals(m_lastValue))
            return;

        m_lastValue = Value;
        vfx.SetBool(m_nameID, Value);
    }
}

[Serializable]
public class ColorVFXProperty : VFXProperty
{
    public Color Value;
    [NonSerialized] Color m_lastValue;

    public override void ApplyToVFX(VisualEffect vfx)
    {
        if (!m_isInitialized)
        {
            Initialize();
            m_lastValue = Value;
        }

        if (!m_isInitialized) return; // Guard against empty name

        if (Value.Equals(m_lastValue))
            return;

        m_lastValue = Value;
        vfx.SetVector4(m_nameID, Value);
    }
}

[Serializable]
public class FloatVFXProperty : VFXProperty
{
    public float Value;
    [NonSerialized] float m_lastValue;

    public override void ApplyToVFX(VisualEffect vfx)
    {
        if (!m_isInitialized)
        {
            Initialize();
            m_lastValue = Value;
        }

        if (!m_isInitialized) return; // Guard against empty name

        if (Value.Equals(m_lastValue))
            return;

        m_lastValue = Value;
        vfx.SetFloat(m_nameID, Value);
    }
}

[Serializable]
public class GradientVFXProperty : VFXProperty
{
    public Gradient Value;

    public override void ApplyToVFX(VisualEffect vfx)
    {
        if (!m_isInitialized)
        {
            Initialize();
        }

        if (!m_isInitialized) return; // Guard against empty name

        vfx.SetGradient(m_nameID, Value);
    }
}

[Serializable]
public class GraphicsBufferVFXProperty : VFXProperty
{
    public GraphicsBuffer Value;

    public override void ApplyToVFX(VisualEffect vfx)
    {
        if (!m_isInitialized)
        {
            Initialize();
        }

        if (!m_isInitialized) return; // Guard against empty name

        vfx.SetGraphicsBuffer(m_nameID, Value);
    }
}

[Serializable]
public class IntVFXProperty : VFXProperty
{
    public int Value;
    [NonSerialized] int m_lastValue;

    public override void ApplyToVFX(VisualEffect vfx)
    {
        if (!m_isInitialized)
        {
            Initialize();
            m_lastValue = Value;
        }

        if (!m_isInitialized) return; // Guard against empty name

        if (Value.Equals(m_lastValue))
            return;

        m_lastValue = Value;
        vfx.SetInt(m_nameID, Value);
    }
}

[Serializable]
public class Matrix4x4VFXProperty : VFXProperty
{
    public Matrix4x4 Value;
    [NonSerialized] Matrix4x4 m_lastValue;

    public override void ApplyToVFX(VisualEffect vfx)
    {
        if (!m_isInitialized)
        {
            Initialize();
            m_lastValue = Value;
        }

        if (!m_isInitialized) return; // Guard against empty name

        if (Value.Equals(m_lastValue))
            return;

        m_lastValue = Value;
        vfx.SetMatrix4x4(m_nameID, Value);
    }
}

[Serializable]
public class MeshVFXProperty : VFXProperty
{
    public Mesh Value;

    public override void ApplyToVFX(VisualEffect vfx)
    {
        if (!m_isInitialized)
        {
            Initialize();
        }

        if (!m_isInitialized) return; // Guard against empty name

        vfx.SetMesh(m_nameID, Value);
    }
}

[Serializable]
public class SkinnedMeshRendererVFXProperty : VFXProperty
{
    public SkinnedMeshRenderer Value;

    public override void ApplyToVFX(VisualEffect vfx)
    {
        if (!m_isInitialized)
        {
            Initialize();
        }

        if (!m_isInitialized) return; // Guard against empty name

        vfx.SetSkinnedMeshRenderer(m_nameID, Value);
    }
}

[Serializable]
public class TextureVFXProperty : VFXProperty
{
    public Texture Value;

    public override void ApplyToVFX(VisualEffect vfx)
    {
        if (!m_isInitialized)
        {
            Initialize();
        }

        if (!m_isInitialized) return; // Guard against empty name

        vfx.SetTexture(m_nameID, Value);
    }
}

[Serializable]
public class UIntVFXProperty : VFXProperty
{
    public uint Value;
    [NonSerialized] uint m_lastValue;

    public override void ApplyToVFX(VisualEffect vfx)
    {
        if (!m_isInitialized)
        {
            Initialize();
            m_lastValue = Value;
        }

        if (!m_isInitialized) return; // Guard against empty name

        if (Value.Equals(m_lastValue))
            return;

        m_lastValue = Value;
        vfx.SetUInt(m_nameID, Value);
    }
}

[Serializable]
public class Vector2VFXProperty : VFXProperty
{
    public Vector2 Value;
    [NonSerialized] Vector2 m_lastValue;

    public override void ApplyToVFX(VisualEffect vfx)
    {
        if (!m_isInitialized)
        {
            Initialize();
            m_lastValue = Value;
        }

        if (!m_isInitialized) return; // Guard against empty name

        if (Value.Equals(m_lastValue))
            return;

        m_lastValue = Value;
        vfx.SetVector2(m_nameID, Value);
    }
}

[Serializable]
public class Vector3VFXProperty : VFXProperty
{
    public Vector3 Value;
    [NonSerialized] Vector3 m_lastValue;

    public override void ApplyToVFX(VisualEffect vfx)
    {
        if (!m_isInitialized)
        {
            Initialize();
            m_lastValue = Value;
        }

        if (!m_isInitialized) return; // Guard against empty name

        if (Value.Equals(m_lastValue))
            return;

        m_lastValue = Value;
        vfx.SetVector3(m_nameID, Value);
    }
}

[Serializable]
public class Vector4VFXProperty : VFXProperty
{
    public Vector4 Value;
    [NonSerialized] Vector4 m_lastValue;

    public override void ApplyToVFX(VisualEffect vfx)
    {
        if (!m_isInitialized)
        {
            Initialize();
            m_lastValue = Value;
        }

        if (!m_isInitialized) return; // Guard against empty name

        if (Value.Equals(m_lastValue))
            return;

        m_lastValue = Value;
        vfx.SetVector4(m_nameID, Value);
    }
}

